apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: $domain
  namespace: traefik
spec:
  secretName: $tls_secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.$domain"
  dnsNames:
  - "*.$domain"
  - $domain
