apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: $traefik_domain
  namespace: traefik
spec:
  secretName: $traefik_secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.$traefik_domain"
  dnsNames:
  - "*.$traefik_domain"
  - $traefik_domain
